name: Test
on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        php: ['7.2', '7.4']
        wp: ['*', 'dev-nightly']
      fail-fast: false
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install PHP
      uses: shivammathur/setup-php@2.7.0
      with:
        php-version: ${{ matrix.php }}
        extensions: mysqli, xmlwriter
        coverage: none
        tools: composer:v1

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version
        node -v
        npm -v
        mysql --version

    - name: Get Composer Cache Directory
      id: composer-cache-dir
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache PHP Dependencies
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

    - name: Install PHP Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest --no-interaction
        composer require --dev --prefer-dist --no-progress --no-suggest --no-interaction --update-with-dependencies roots/wordpress="${{ matrix.wp }} || *" wp-phpunit/wp-phpunit="${{ matrix.wp }} || *"

    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
        echo "::set-output name=npm-version::$(npm -v)"
        echo "::set-output name=node-version::$(node-v)"

    - name: Cache JS Dependencies
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-${{ steps.npm-cache-dir.outputs.node-version }}-${{ steps.npm-cache-dir.outputs.npm-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install JS Dependencies
      run: npm install

    - name: PHPCS cache
      uses: actions/cache@v2
      with:
        path: tests/cache
        key: ${{ matrix.php }}-phpcs-${{ hashFiles('plugin.php') }}

    - name: Run the tests
      run: |
        sudo systemctl start mysql.service
        npm run lint
        npm run build
        composer test
      env:
        MYSQL_DATABASE: wordpress
        WP_TESTS_DB_PASS: root
